### ISSUE TITLE
The problem of generating cube files for visualizing NTO orbitals

### ISSUE THREAD

**Issue by Quark195** [felixplasser/theodore-qc#27]
Dear developers! I ran into a problem while generating cube files with Theodore 2.5.0. I used the Orca 5.0.1 inp file from the Theodore examples folder as input. If I use the command `cube_orbitals = True` for Orbkit I get the following error:
```
Calculating NTOs as cube files with Orbkit for state 1(1)A
Traceback (most recent call last):
  File "/home/quark/.local/bin/theodore", line 8, in <module>
    sys.exit(run())
  File "/home/quark/.local/lib/python3.8/site-packages/colt/colt.py", line 347, in __call__
    return self._cls.from_commandline(*args, description=self.description,
  File "/home/quark/.local/lib/python3.8/site-packages/colt/colt.py", line 243, in from_commandline
    return cls.from_config(answers, *args, **kwargs)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/actions.py", line 21, in from_config
    return action.from_config(config)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/actions.py", line 33, in from_config
    return cls.run(**config)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/theotools.py", line 31, in _wrapper
    result = func(*args, **kwargs)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/analyze_tden.py", line 43, in run
    tdena.compute_all_NTO()
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/lib_tden.py", line 441, in compute_all_NTO
    cbfid = lib_orbkit.cube_file_creator(state, U, lam, Vt, self.mos,minlam=self.ioptions['min_occ'],numproc=self.ioptions.get('numproc'))
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/orbkit_full.py", line 193, in cube_file_creator
    qc = self.orbkit_geo_ao_conversion(mos)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/orbkit_full.py", line 43, in orbkit_geo_ao_conversion
    qc = read.read_molden(tmp.name)
  File "/home/quark/Orbkit/orbkit/orbkit/read/molden.py", line 370, in read_molden
    sym = sym[0].split('.')[-1]
IndexError: list index out of range
```

If you use the command `vmd_ntos = True for VMD`, then the program gives the following error
```
VMD network for NTOs
Traceback (most recent call last):
  File "/home/quark/.local/bin/theodore", line 8, in <module>
    sys.exit(run())
  File "/home/quark/.local/lib/python3.8/site-packages/colt/colt.py", line 347, in __call__
    return self._cls.from_commandline(*args, description=self.description,
  File "/home/quark/.local/lib/python3.8/site-packages/colt/colt.py", line 243, in from_commandline
    return cls.from_config(answers, *args, **kwargs)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/actions.py", line 21, in from_config
    return action.from_config(config)
  File "/home/quark/.local/lib/pytho
[error.zip](https://github.com/felixplasser/theodore-qc/files/7493661/error.zip)
n3.8/site-packages/theodore/actions/actions.py", line 33, in from_config
    return cls.run(**config)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/theotools.py", line 31, in _wrapper
    result = func(*args, **kwargs)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/analyze_tden.py", line 43, in run
    tdena.compute_all_NTO()
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/lib_tden.py", line 446, in compute_all_NTO
    lib_orbkit.vmd_network_creator(filename='NTOs',cube_ids=numpy.hstack(cube_ids),isovalue=self.ioptions.get('vmd_ntos_iv'))
UnboundLocalError: local variable 'lib_orbkit' referenced before assignment
```

When I turn off file cube creation, the analysis finishes without errors. If there is a way to resolve this error?
The calculation files are attached.[error.zip](https://github.com/felixplasser/theodore-qc/files/7493666/error.zip)

Thank you very much for your attention.
Best regards, Eugene

**Comment by felixplasser** [comment]
Hi, the first problem is about reading the Molden file. This should be fixed in my local orbkit branch, here
https://github.com/orbkit/orbkit/commit/06381fbb212f498ff391937c962285a1f2915ecb

Let me know how things go. I am a bit behind on code maintenance. But I hope it won't be too hard to get this up and running.

**Comment by Quark195** [comment]
Dear Prof. Felix,
thanks for answering my request.
Unfortunately, using the submitted version of Orbkit did not fix the error.
I've already tried using different versions of Orbkit, but they all give an error when generating cube files.

https://github.com/felixplasser/orbkit
https://github.com/orbkit/orbkit

```
Traceback (most recent call last):
  File "/home/quark/.local/bin/theodore", line 8, in <module>
    sys.exit(run())
  File "/home/quark/.local/lib/python3.8/site-packages/colt/colt.py", line 347, in __call__
    return self._cls.from_commandline(*args, description=self.description,
  File "/home/quark/.local/lib/python3.8/site-packages/colt/colt.py", line 243, in from_commandline
    return cls.from_config(answers, *args, **kwargs)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/actions.py", line 21, in from_config
    return action.from_config(config)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/actions.py", line 33, in from_config
    return cls.run(**config)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/theotools.py", line 31, in _wrapper
    result = func(*args, **kwargs)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/analyze_tden.py", line 43, in run
    tdena.compute_all_NTO()
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/lib_tden.py", line 441, in compute_all_NTO
    cbfid = lib_orbkit.cube_file_creator(state, U, lam, Vt, self.mos,minlam=self.ioptions['min_occ'],numproc=self.ioptions.get('numproc'))
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/orbkit_full.py", line 193, in cube_file_creator
    qc = self.orbkit_geo_ao_conversion(mos)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/orbkit_full.py", line 43, in orbkit_geo_ao_conversion
    qc = read.read_molden(tmp.name)
  File "/home/quark/Orbkit3/orbkit/orbkit/read/molden.py", line 370, in read_molden
    sym = sym[0].split('.')[-1]
IndexError: list index out of range

```
and for VMD 
```
VMD network for NTOs
Traceback (most recent call last):
  File "/home/quark/.local/bin/theodore", line 8, in <module>
    sys.exit(run())
  File "/home/quark/.local/lib/python3.8/site-packages/colt/colt.py", line 347, in __call__
    return self._cls.from_commandline(*args, description=self.description,
  File "/home/quark/.local/lib/python3.8/site-packages/colt/colt.py", line 243, in from_commandline
    return cls.from_config(answers, *args, **kwargs)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/actions.py", line 21, in from_config
    return action.from_config(config)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/actions.py", line 33, in from_config
    return cls.run(**config)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/theotools.py", line 31, in _wrapper
    result = func(*args, **kwargs)
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/analyze_tden.py", line 43, in run
    tdena.compute_all_NTO()
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/lib_tden.py", line 446, in compute_all_NTO
    lib_orbkit.vmd_network_creator(filename='NTOs',cube_ids=numpy.hstack(cube_ids),isovalue=self.ioptions.get('vmd_ntos_iv'))
UnboundLocalError: local variable 'lib_orbkit' referenced before assignment
```
I have also tested different versions of Theodore
https://sourceforge.net/projects/theodore-qc/ 
https://fplasser.sci-public.lboro.ac.uk/2021/04/22/release-of-theodore-2-4/



Best regards, Eugene
